0.000	12.240	 lesson 13 the little dragon the children put on a play I am the king said chip
12.240	23.880	 fight the dragon I am the night said Wilma I will fight the dragon I am the
24.320	37.800	 said Kipper but I am a little dragon I am the princess said Biff I like dragons
37.800	53.120	 the princess played with the dragon they played under the tree I am the night said Wilma I am
53.160	64.320	 frightened said the dragon I am cross said the princess she pushed the night in the pond
64.320	69.080	 what a good play said everyone
