0.000	11.280	 lesson 15 new trees the children went to the park it was give a tree week
11.280	19.760	 everyone wanted to give trees dad gave a tree he put it by the shed
19.760	27.280	 Chip gave a tree he put it by the stream Biff gave a tree
27.400	36.720	 she put it by the pond wolf gave a tree he put it by the bridge Wilma gave a
36.720	47.720	 tree she put it by the swing floppy gave a bone he put it in a hole a funny
47.720	54.440	 tree said chip a funny bone said dad
