0.000	12.320	 lesson 16 the band dad played his trumpet he played in the house floppy
12.320	23.160	 barks at dad dad played in the garage floppy barks at dad dad played in the
23.160	35.840	 shed floppy barked at dad dad played in a band the band played in the park floppy
35.840	49.400	 went to the park the band played floppy barked floppy barked and barked the band
49.400	54.640	 couldn't play what a bad dog said dad
