0.000	3.000	 The Dream
3.000	8.000	 Biff couldn't sleep.
8.000	12.000	 Dad told her a story.
12.000	17.000	 The story was about a dragon.
17.000	23.000	 Biff dreamed about the dragon.
23.000	29.000	 It was a nasty dragon.
29.000	35.000	 It was a very nasty dragon.
35.000	41.000	 Biff had to fight it.
41.000	46.000	 Biff went downstairs.
46.000	50.000	 Mum told her a story.
50.000	56.000	 The story was about a dolphin.
56.000	61.000	 Biff dreamed about a dolphin.
